apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-master-svc
spec:
  selector:
    app: {{ .Release.Name }}-master
  ports:
    - protocol: TCP
      name: pg
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-slave-svc
spec:
  selector:
    app: {{ .Release.Name }}-slave
  ports:
    - protocol: TCP
      name: pg
      port: 6379
      targetPort: 6379